"""
obi — Ontological Bayesian Intelligence v0.1.0 "Phoenix Rising"

Package hierarchy (agents.md §2.2):

    obi.core.*        Core inference engine (transitioning to pure Python)
    obi.cognition.*   Python orchestration: Filter-Flash, dimensional strategy
    obi.memory.*      Memory management: DIRAM gates, consciousness stack
    obi.integrity.*   Security: AuraSeal, ZID auth
    obi.data.*        Python: marshalling, polyglot adapters
    obi.telemetry.*   Python: intention promotion, sensor fusion

Entry-point for OBI debiasing, drift mitigation, and reasoning:

    import obi

    data = obi.dataset(X, y, protected=A)
    result = obi.debias(data, graph)
    drift = obi.mitigate_drift(current, baseline)
"""

from obi.sdk.core import OBIContext, ReasoningResult
from obi.api import (
    BiasReport,
    C_COHERENCE,
    CircuitBreaker,
    DAG,
    DIRAMCascade,
    DRIFT_BOUND_MAX,
    DataPoint,
    Dataset,
    DebiasResult,
    DriftObservation,
    DriftResult,
    FairnessValidationError,
    FilterFlashEngine,
    FlashMemoryEntry,
    IntegrityStatus,
    LAMBDA_DECAY_DEFAULT,
    MALPAARTICEFramework,
    ProcessedOutput,
    StorageRecord,
    TriangiReport,
    ValidationReport,
    Variable,
    ZoneResponse,
    array,
    audit,
    backdoors,
    bias_reduction,
    block_backdoors,
    classify_drift_vector,
    classify_drift_zone,
    content_hash,
    context,
    cosine_dissimilarity,
    dag,
    data_point,
    dataset,
    debias,
    demographic_parity_gap,
    diram_cascade,
    drift_measure,
    drift_observation,
    dump,
    dump_manifest,
    edge,
    entropy,
    factorize,
    filter_flash_engine,
    filter_layer,
    flash_age_check,
    flash_layer,
    get_context,
    kl,
    kl_divergence,
    malpaartice_framework,
    mitigate_drift,
    normalize,
    pipeline,
    prediction_rate,
    scale_to_failure_range,
    state_confidence,
    storage_layer,
    temporal_shift,
    triangi_validate,
    validate,
    variable,
    zone_response,
)
from obi.core import (
    Config,
    DataProbeAdapter,
    ProbeEngine,
    ProbeResult,
    external_probe,
    internal_probe,
    probe_alignment,
)

__version__ = "0.1.0-alpha"
__author__ = "Nnamdi Michael Okpala (OBINexus)"

__all__ = [
    "BiasReport",
    "C_COHERENCE",
    "CircuitBreaker",
    "DAG",
    "DIRAMCascade",
    "DRIFT_BOUND_MAX",
    "DataPoint",
    "Dataset",
    "DebiasResult",
    "DriftObservation",
    "DriftResult",
    "FairnessValidationError",
    "FilterFlashEngine",
    "FlashMemoryEntry",
    "IntegrityStatus",
    "LAMBDA_DECAY_DEFAULT",
    "MALPAARTICEFramework",
    "ProcessedOutput",
    "StorageRecord",
    "TriangiReport",
    "ValidationReport",
    "Variable",
    "ZoneResponse",
    "OBIContext",
    "ReasoningResult",
    "Config",
    "ProbeEngine",
    "ProbeResult",
    "DataProbeAdapter",
    "internal_probe",
    "external_probe",
    "probe_alignment",
    "array",
    "audit",
    "backdoors",
    "bias_reduction",
    "block_backdoors",
    "classify_drift_vector",
    "classify_drift_zone",
    "content_hash",
    "context",
    "cosine_dissimilarity",
    "dag",
    "data_point",
    "dataset",
    "debias",
    "demographic_parity_gap",
    "diram_cascade",
    "drift_measure",
    "drift_observation",
    "dump",
    "dump_manifest",
    "edge",
    "entropy",
    "factorize",
    "filter_flash_engine",
    "filter_layer",
    "flash_age_check",
    "flash_layer",
    "get_context",
    "kl",
    "kl_divergence",
    "malpaartice_framework",
    "mitigate_drift",
    "normalize",
    "pipeline",
    "prediction_rate",
    "scale_to_failure_range",
    "state_confidence",
    "storage_layer",
    "temporal_shift",
    "triangi_validate",
    "validate",
    "variable",
    "zone_response",
]
